name: Run Web Scrapers

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch the last 2 commits to check commit message

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt

      - name: Run first script for Summer and Fall 2025
        run: python pythonScripts/UFCourseGrabber.py summer 25 fall 25 spring 26

      - name: Run second script
        run: python pythonScripts/scrapeRMP.py

      - name: Configure Git
        run: |
          git config --global user.email "andy.chen0607@gmail.com"
          git config --global user.name "andychen482"
          git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/andychen482/UF-Scheduler-Backend.git

      - name: Commit and conditionally amend previous commit
        run: |
          git add -A
          if ! git diff --staged --quiet; then
            LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
            if [ "$LAST_COMMIT_MSG" = "Hourly update from web scrapers" ]; then
              git commit --amend --no-edit
            else
              git commit -m "Hourly update from web scrapers"
            fi
            git push --force
          fi
